repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^(notebooks|groovy)/
      - id: ruff-format
        exclude: ^(notebooks|groovy)/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(notebooks|groovy)/
      - id: end-of-file-fixer
        exclude: ^(notebooks|groovy)/
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
        exclude: ^(notebooks|groovy)/
